import { AboutIllustration } from '@/components/images/about-ilustration';
import { AppIllustration } from '@/components/images/app-ilustration';
import { HomeIllustration } from '@/components/images/home-ilustration';
import { SecurityIllustration } from '@/components/images/security-ilustration';
import { ServiceIllustration1 } from '@/components/images/services1-ilustration';
import { ServiceIllustration2 } from '@/components/images/services2-ilustration';
import { ServiceIllustration3 } from '@/components/images/services3-ilustration';
import Head from 'next/head'
import { BiToggleLeft, BiToggleRight } from 'react-icons/bi';
import { BiGridAlt } from 'react-icons/bi';
import { BiUpArrowAlt } from 'react-icons/bi';
import React, { useState, useEffect } from 'react';

//const inter = Inter({ subsets: ['latin'] })
export default function Home() {
  let [darkTheme, setDarkTheme] = useState<Boolean>()
  useEffect(() => {
    /*=============== SCROLL SECTIONS ACTIVE LINK ===============*/
    const sections = document.querySelectorAll <HTMLElement>('section[id]')
    function scrollActive(){
      const scrollY = window.pageYOffset
      
      sections.forEach(current =>{
          const sectionHeight = current.offsetHeight,
                sectionTop = current.offsetTop - 50,
                sectionId = current.getAttribute('id')
          if(scrollY+300 > sectionTop && scrollY <= sectionTop + sectionHeight){
              document.querySelector('.nav__menu a[href*=' + sectionId + ']')!.classList.add('active-link')!
          }else{
              document.querySelector('.nav__menu a[href*=' + sectionId + ']')!.classList.remove('active-link')!
          }
      }) 
    }
    window.addEventListener('scroll', scrollActive)

    /*=============== CHANGE BACKGROUND HEADER ===============*/
    function scrollHeader(){
      const nav = document.getElementById('header')!
      // When the scroll is greater than 80 viewport height, add the scroll-header class to the header tag
      if(window.scrollY >= 80) nav.classList.add('scroll-header'); else nav.classList.remove('scroll-header')
    }
    window.addEventListener('scroll', scrollHeader)

          
    /*=============== SHOW SCROLL UP ===============*/
    function scrollUp(){
      const scrollUp = document.getElementById('scroll-up')!;
      // When the scroll is higher than 560 viewport height, add the show-scroll class to the a tag with the scroll-top class
      if(window.scrollY >= 560) scrollUp.classList.add('show-scroll'); else scrollUp.classList.remove('show-scroll')
    }
    window.addEventListener('scroll', scrollUp)
   
   /*=============== GET CURRENT THEME FROM LOCAL STORAGE ===============*/
    const currentTheme = localStorage.getItem('selected-theme')
    if(currentTheme === 'dark'){
      handleChangeTheme('dark-button')
    } else {
      handleChangeTheme('light-button')
    }
  },[])




  function handleOpenMenu(navId: string){
      let nav = document.getElementById(navId)
      // Validate that variables exist
      if(nav){
        // We add the show-menu class to the div tag with the nav__menu class
        nav.classList.toggle('show-menu')
      }
  }

  function handleChangeTheme(e) {
    if(e=='dark-button') {
      setDarkTheme(false)
      localStorage.setItem('selected-theme', 'light')
      document.body.classList.remove('dark-theme')
    }else{
      setDarkTheme(true)
      localStorage.setItem('selected-theme', 'dark')
      document.body.classList.add('dark-theme')
      }
  }

  
  return (
    <>
      <Head>
        <title>Index</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/*=============== HEADER ===============*/}
      <header className="header" id="header">
          <nav className="nav container">
              <a href="#" className="nav__logo">Delivery</a>

              <div className="nav__menu" id="nav-menu">
                  <ul className="nav__list">
                      <li className="nav__item">
                          <a href="#home" className="nav__link active-link">Home</a>
                      </li>
                      <li className="nav__item">
                          <a href="#about" className="nav__link">About us</a>
                      </li>
                      <li className="nav__item">
                          <a href="#services" className="nav__link">Services</a>
                      </li>
                      <li className="nav__item">
                          <a href="#contact" className="nav__link">Contact us</a>
                      </li>
                      {
                       darkTheme ? (
                         <BiToggleRight id='dark-button' className='change-theme' onClick={(e) => handleChangeTheme(e.target.id)}/>
                       ):(                         
                          <BiToggleLeft id='light-button' className='change-theme' onClick={(e) => handleChangeTheme(e.target.id)}/>
                        )
                      }
                
                      
                  </ul>
              </div>

              <div className="nav__toggle" id="nav-toggle" >
                   <BiGridAlt id='theme-button' className='change-theme' onClick={() => handleOpenMenu('nav-menu')}/>
              </div>

              <a href="#" className="button button__header">Order Now!</a>
          </nav>
      </header>
      <main className="main">
            {/*=============== HOME ===============*/}
            <section className="home section" id="home">
                <div className="home__container container grid">
                  <HomeIllustration/>
                  <div className="home__data">
                      <h1 className="home__title">Order Products <br/> Faster Easier</h1>
                      <p className="home__description">Order your favorite foods at any time and we will deliver them right to where you are.</p>

                      <a href="#" className="button">Get Started</a>
                      {console.log(darkTheme)}
                  </div>   
                </div>
            </section>

            {/*=============== ABOUT ===============*/}
            <section className="about section container" id="about">
                <div className="about__container grid">
                    <div className="about__data">
                        <h2 className="section__title-center">Find Out A Little More <br/> About Us</h2>
                        <p className="about__description">We are a company dedicated to the distribution of products by delivery 
                            to your home or to the place where you are, with the best quality of delivery.
                        </p>
                    </div>
                    <AboutIllustration/>
                </div>
            </section>

            {/*=============== SECURITY ===============*/}
            <section className="security section container">
                <div className="security__container grid">
                    <div className="security__data">
                        <h2 className="section__title-center">Your Safety Is <br/> Important</h2>
                        <p className="security__description">When your order reaches you, we have the health safety protocols, 
                            so that you are protected from any disease. Watch the video of how the delivery is made.
                        </p>
                    </div>
                    <SecurityIllustration/>                   
                </div>
            </section>

            {/*=============== SERVICES ===============*/}
            <section className="services section container" id="services">
                <h2 className="section__title">Some Services We <br/> Offer</h2>
                <div className="services__container grid">
                    <div className="services__data">
                        <h3 className="services__subtitle">Payment Done</h3>
                        <ServiceIllustration1 />
                        <p className="services__description">Pay with a Visa or PayPal card and without much ado.</p>
                        <div>
                            <a href="#" className="button button-link">Learn More</a>
                        </div>
                    </div>

                    <div className="services__data">
                        <h3 className="services__subtitle">Find Your Product</h3>
                        <ServiceIllustration2 />
                        <p className="services__description">We offer sale of products through the Internet.</p>
                        <div>
                            <a href="#" className="button button-link">Learn More</a>
                        </div>
                    </div>

                    <div className="services__data">
                        <h3 className="services__subtitle">Product Received</h3>
                        <ServiceIllustration3 />
                        <p className="services__description">In our app you can see the delay time of your order.</p>
                        <div>
                            <a href="#" className="button button-link">Learn More</a>
                        </div>
                    </div>
                </div>
            </section>

            {/*=============== APP ===============*/}
            <section className="app section container">
                <div className="app__container grid">
                    <div className="app__data">
                        <h2 className="section__title-center">Watch Your Delivery <br/> At Any Time</h2>
                        <p className="app__description">With our app you can view the route of your order, from our local headquarters to the 
                            place where you are. Look for the app now!</p>
                        <div className="app__buttons">
                            <a href="#" className="button button-flex">
                                <i className='bx bxl-apple button__icon'></i> App Store
                            </a>
                            <a href="#" className="button button-flex">
                                <i className='bx bxl-play-store button__icon' ></i> Google Play
                            </a>
                        </div>
                    </div>

                    <AppIllustration/>
                </div>
            </section>

            {/* =============== CONTACT US =============== */}
            <section className="contact section container" id="contact">
                <div className="contact__container grid">
                    <div className="contact__content">
                        <h2 className="section__title-center">Contact Us From <br/> Here</h2>
                        <p className="contact__description">You can contact us from here, you can write to us, 
                            call us or visit our service center, we will gladly assist you.</p>
                    </div>

                    <ul className="contact__content grid">
                        <li className="contact__address">Telephone: <span className="contact__information">999 - 888 - 777</span></li>
                        <li className="contact__address">Email:  <span className="contact__information">delivery@email.com</span></li>
                        <li className="contact__address">Location: <span className="contact__information">Lima - Peru</span></li>
                    </ul>

                    <div className="contact__content">
                        <a href="#" className="button">Contact Us</a>
                    </div>
                </div>
            </section>
        </main>
        {/*=============== SCROLL UP ===============*/}
        <a href="#" className="scrollup" id="scroll-up">
          <BiUpArrowAlt className='scrollup__icon'/>
        </a>

        {/*=============== MAIN JS ===============*/}

    </>
  )
}
