import { AboutIllustration } from '@/components/images/about-ilustration';
import { AppIllustration } from '@/components/images/app-ilustration';
import { HomeIllustration } from '@/components/images/home-ilustration';
import { SecurityIllustration } from '@/components/images/security-ilustration';
import { ServiceIllustration1 } from '@/components/images/services1-ilustration';
import { ServiceIllustration2 } from '@/components/images/services2-ilustration';
import { ServiceIllustration3 } from '@/components/images/services3-ilustration';
import Head from 'next/head'
import { BiToggleLeft } from 'react-icons/bi';

//const inter = Inter({ subsets: ['latin'] })
export default function Home() {

  function handleShowMenu(){
  /*=============== SHOW MENU ===============*/
  const showMenu = (toggleId, navId) => {
    const toggle = document.getElementById(toggleId),
    nav = document.getElementById(navId)
    
    // Validate that variables exist
    if(toggle && nav){
        toggle.addEventListener('click', ()=>{
            // We add the show-menu class to the div tag with the nav__menu class
            nav.classList.toggle('show-menu')
        })
    }
  }
  showMenu('nav-toggle','nav-menu')
  
/*=============== REMOVE MENU MOBILE ===============*/
const navLink = document.querySelectorAll('.nav__link')

function linkAction(){
  const navMenu = document.getElementById('nav-menu')
  // When we click on each nav__link, we remove the show-menu class
  navMenu.classList.remove('show-menu')
}
navLink.forEach(n => n.addEventListener('click', linkAction))

/*=============== SCROLL SECTIONS ACTIVE LINK ===============*/
const sections = document.querySelectorAll('section[id]')

function scrollActive(){
  const scrollY = window.pageYOffset

  sections.forEach(current =>{
      const sectionHeight = current.offsetHeight,
            sectionTop = current.offsetTop - 50,
            sectionId = current.getAttribute('id')

      if(scrollY > sectionTop && scrollY <= sectionTop + sectionHeight){
          document.querySelector('.nav__menu a[href*=' + sectionId + ']').classList.add('active-link')
      }else{
          document.querySelector('.nav__menu a[href*=' + sectionId + ']').classList.remove('active-link')
      }
  })
}
window.addEventListener('scroll', scrollActive)

/*=============== CHANGE BACKGROUND HEADER ===============*/
function scrollHeader(){
  const nav = document.getElementById('header')
  // When the scroll is greater than 80 viewport height, add the scroll-header class to the header tag
  if(this.scrollY >= 80) nav.classList.add('scroll-header'); else nav.classList.remove('scroll-header')
}
window.addEventListener('scroll', scrollHeader)

/*=============== SHOW SCROLL UP ===============*/
function scrollUp(){
  const scrollUp = document.getElementById('scroll-up');
  // When the scroll is higher than 560 viewport height, add the show-scroll class to the a tag with the scroll-top class
  if(this.scrollY >= 560) scrollUp.classList.add('show-scroll'); else scrollUp.classList.remove('show-scroll')
}
window.addEventListener('scroll', scrollUp)

/*=============== DARK LIGHT THEME ===============*/
const themeButton = document.getElementById('theme-button')
const darkTheme = 'dark-theme'
const iconTheme = 'bx-toggle-right'

// Previously selected topic (if user selected)
const selectedTheme = localStorage.getItem('selected-theme')
const selectedIcon = localStorage.getItem('selected-icon')

// We obtain the current theme that the interface has by validating the dark-theme class
const getCurrentTheme = () => document.body.classList.contains(darkTheme) ? 'dark' : 'light'
const getCurrentIcon = () => themeButton.classList.contains(iconTheme) ? 'bx-toggle-left' : 'bx-toggle-right'

// We validate if the user previously chose a topic
if (selectedTheme) {
// If the validation is fulfilled, we ask what the issue was to know if we activated or deactivated the dark
document.body.classList[selectedTheme === 'dark' ? 'add' : 'remove'](darkTheme)
themeButton.classList[selectedIcon === 'bx-toggle-left' ? 'add' : 'remove'](iconTheme)
}

// Activate / deactivate the theme manually with the button
themeButton.addEventListener('click', () => {
  // Add or remove the dark / icon theme
  document.body.classList.toggle(darkTheme)
  themeButton.classList.toggle(iconTheme)
  // We save the theme and the current icon that the user chose
  localStorage.setItem('selected-theme', getCurrentTheme())
  localStorage.setItem('selected-icon', getCurrentIcon())
})
  }
  return (
    <>
      <Head>
        <title>Index</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/*=============== HEADER ===============*/}
      <header className="header" id="header">
          <nav className="nav container">
              <a href="#" className="nav__logo">Delivery</a>

              <div className="nav__menu" id="nav-menu">
                  <ul className="nav__list">
                      <li className="nav__item">
                          <a href="#home" className="nav__link active-link">Home</a>
                      </li>
                      <li className="nav__item">
                          <a href="#about" className="nav__link">About us</a>
                      </li>
                      <li className="nav__item">
                          <a href="#services" className="nav__link">Services</a>
                      </li>
                      <li className="nav__item">
                          <a href="#contact" className="nav__link">Contact us</a>
                      </li>
                      <BiToggleLeft id='nav-toggle' className='change-theme' />
                  </ul>
              </div>

              <div className="nav__toggle" id="nav-toggle">
                  <i className='bx bx-grid-alt'></i>
              </div>

              <a href="#" className="button button__header">Order Now!</a>
          </nav>
      </header>
      <main className="main">
            {/*=============== HOME ===============*/}
            <section className="home section" id="home">
                <div className="home__container container grid">
                  <HomeIllustration/>
                  <div className="home__data">
                      <h1 className="home__title">Order Products <br/> Faster Easier</h1>
                      <p className="home__description">Order your favorite foods at any time and we will deliver them right to where you are.</p>

                      <a href="#" className="button">Get Started</a>

                  </div>   
                </div>
            </section>

            {/*=============== ABOUT ===============*/}
            <section className="about section container" id="about">
                <div className="about__container grid">
                    <div className="about__data">
                        <h2 className="section__title-center">Find Out A Little More <br/> About Us</h2>
                        <p className="about__description">We are a company dedicated to the distribution of products by delivery 
                            to your home or to the place where you are, with the best quality of delivery.
                        </p>
                    </div>
                    <AboutIllustration/>
                </div>
            </section>

            {/*=============== SECURITY ===============*/}
            <section className="security section container">
                <div className="security__container grid">
                    <div className="security__data">
                        <h2 className="section__title-center">Your Safety Is <br/> Important</h2>
                        <p className="security__description">When your order reaches you, we have the health safety protocols, 
                            so that you are protected from any disease. Watch the video of how the delivery is made.
                        </p>
                    </div>
                    <SecurityIllustration/>                   
                </div>
            </section>

            {/*=============== SERVICES ===============*/}
            <section className="services section container" id="services">
                <h2 className="section__title">Some Services We <br/> Offer</h2>
                <div className="services__container grid">
                    <div className="services__data">
                        <h3 className="services__subtitle">Payment Done</h3>
                        <ServiceIllustration1 />
                        <p className="services__description">Pay with a Visa or PayPal card and without much ado.</p>
                        <div>
                            <a href="#" className="button button-link">Learn More</a>
                        </div>
                    </div>

                    <div className="services__data">
                        <h3 className="services__subtitle">Find Your Product</h3>
                        <ServiceIllustration2 />
                        <p className="services__description">We offer sale of products through the Internet.</p>
                        <div>
                            <a href="#" className="button button-link">Learn More</a>
                        </div>
                    </div>

                    <div className="services__data">
                        <h3 className="services__subtitle">Product Received</h3>
                        <ServiceIllustration3 />
                        <p className="services__description">In our app you can see the delay time of your order.</p>
                        <div>
                            <a href="#" className="button button-link">Learn More</a>
                        </div>
                    </div>
                </div>
            </section>

            {/*=============== APP ===============*/}
            <section className="app section container">
                <div className="app__container grid">
                    <div className="app__data">
                        <h2 className="section__title-center">Watch Your Delivery <br/> At Any Time</h2>
                        <p className="app__description">With our app you can view the route of your order, from our local headquarters to the 
                            place where you are. Look for the app now!</p>
                        <div className="app__buttons">
                            <a href="#" className="button button-flex">
                                <i className='bx bxl-apple button__icon'></i> App Store
                            </a>
                            <a href="#" className="button button-flex">
                                <i className='bx bxl-play-store button__icon' ></i> Google Play
                            </a>
                        </div>
                    </div>

                    <AppIllustration/>
                </div>
            </section>

            {/* =============== CONTACT US =============== */}
            <section className="contact section container" id="contact">
                <div className="contact__container grid">
                    <div className="contact__content">
                        <h2 className="section__title-center">Contact Us From <br/> Here</h2>
                        <p className="contact__description">You can contact us from here, you can write to us, 
                            call us or visit our service center, we will gladly assist you.</p>
                    </div>

                    <ul className="contact__content grid">
                        <li className="contact__address">Telephone: <span className="contact__information">999 - 888 - 777</span></li>
                        <li className="contact__address">Email:  <span className="contact__information">delivery@email.com</span></li>
                        <li className="contact__address">Location: <span className="contact__information">Lima - Peru</span></li>
                    </ul>

                    <div className="contact__content">
                        <a href="#" className="button">Contact Us</a>
                    </div>
                </div>
            </section>
        </main>
        {/*=============== FOOTER ===============*/}
        <footer className="footer section">
            <div className="footer__container container grid">
                <div className="footer__content">
                    <a href="#" className="footer__logo">Delivery</a>
                    <p className="footer__description">Order Products Faster <br/> Easier</p>
                </div>

                <div className="footer__content">
                    <h3 className="footer__title">Our Services</h3>
                    <ul className="footer__links">
                        <li><a href="#" className="footer__link">Pricing </a></li>
                        <li><a href="#" className="footer__link">Discounts</a></li>
                        <li><a href="#" className="footer__link">Report a bug</a></li>
                        <li><a href="#" className="footer__link">Terms of Service</a></li>
                    </ul>
                </div>

                <div className="footer__content">
                    <h3 className="footer__title">Our Company</h3>
                    <ul className="footer__links">
                        <li><a href="#" className="footer__link">Blog</a></li>
                        <li><a href="#" className="footer__link">Our mision</a></li>
                        <li><a href="#" className="footer__link">Get in touch</a></li>
                    </ul>
                </div>

                <div className="footer__content">
                    <h3 className="footer__title">Community</h3>
                    <ul className="footer__links">
                        <li><a href="#" className="footer__link">Support</a></li>
                        <li><a href="#" className="footer__link">Questions</a></li>
                        <li><a href="#" className="footer__link">Customer help</a></li>
                    </ul>
                </div>

                <div className="footer__social">
                    <a href="#" className="footer__social-link"><i className='bx bxl-facebook-circle '></i></a>
                    <a href="#" className="footer__social-link"><i className='bx bxl-twitter'></i></a>
                    <a href="#" className="footer__social-link"><i className='bx bxl-instagram-alt'></i></a>
                </div>
            </div>

            <p className="footer__copy">&#169; Bedimcode. All right reserved</p>
        </footer>
        {/*=============== SCROLL UP ===============*/}
        <a href="#" className="scrollup" id="scroll-up">
            <i className='bx bx-up-arrow-alt scrollup__icon'>top</i>
        </a>

        {/*}=============== MAIN JS ===============*/}
        <script src="assets/js/main.js"></script>

    </>
  )
}
